development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: study_room_production
  allow_request_origin:
    - https://study-room-rails7.onrender.com
